# Generated by Django 2.2 on 2019-04-20 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('keyword', models.TextField(blank=True, verbose_name='關鍵字')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='連結')),
                ('body', models.TextField(verbose_name='文章內容')),
                ('readcount', models.IntegerField(default=0, verbose_name='閱讀次數')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='發佈日期')),
            ],
            options={
                'verbose_name': '部落格文章',
                'verbose_name_plural': '部落格',
                'ordering': ('-pub_date',),
            },
        ),
    ]
